# .github/workflows/blog.yml
name: Auto-build blog index

on:
  push:
    paths:
      - '_blogs/**.md'
      - 'scripts/build_blog_index.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install gray-matter

      - name: Build blog index
        run: node scripts/build_blog_index.js

      - name: Commit updated index
        run: |
          git config user.name  'github-actions'
          git config user.email 'actions@github.com'
          git add blogs.json
          git commit -m "chore: update blog index" || echo "No changes to commit"
          git push
